# Generated by Django 5.1.7 on 2025-04-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_status_order_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent_id',
        ),
    ]
