# Generated by Django 5.1.7 on 2025-06-03 13:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('shirt', 'Shirt'), ('pant', 'Pant'), ('underwear', 'Underwear'), ('t_shirt', 'T-Shirt'), ('polo_shirt', 'Polo Shirt'), ('combo', 'Combo'), ('trouser', 'Trouser'), ('shock', 'Shock'), ('muffler', 'Muffler'), ('full_sleeve_shirt', 'Full Sleeve Shirt'), ('jacket', 'Jacket'), ('sweater', 'Sweater'), ('huddy', 'Huddy'), ('cargo_shorts', 'Cargo Shorts'), ('jersey', 'Jersey')], default='shirt', max_length=50)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_image')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('colors', models.ManyToManyField(blank=True, related_name='products', to='products.color')),
                ('sizes', models.ManyToManyField(blank=True, related_name='products', to='products.size')),
            ],
        ),
    ]
