# Generated by Django 5.1.7 on 2025-04-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_created_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('pant', 'Pant'), ('underwear', 'Underwear'), ('t_shirt', 'T-Shirt'), ('polo_shirt', 'Polo Shirt'), ('combo', 'Combo'), ('trouser', 'Trouser'), ('shock', 'Shock'), ('muffler', 'Muffler'), ('full_sleeve_shirt', 'Full Sleeve Shirt'), ('jacket', 'Jacket'), ('sweater', 'Sweater'), ('huddy', 'Huddy'), ('cargo_shorts', 'Cargo Shorts'), ('jersey', 'Jersey')], default='shirt', max_length=50),
        ),
    ]
