# Generated by Django 5.1.7 on 2025-04-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
