# Generated by Django 5.1.7 on 2025-04-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='state',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('checked_out', 'Checked Out')], default='active', max_length=20),
        ),
    ]
