# Generated by Django 5.1.7 on 2025-03-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('USER', 'user')], default='USER', max_length=20),
        ),
    ]
