# Generated by Django 5.1.7 on 2025-04-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
